# Generated by Django 4.0.6 on 2022-07-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate', models.CharField(max_length=200)),
                ('diameter', models.IntegerField()),
                ('gravity', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('orbital_period', models.IntegerField()),
                ('population', models.IntegerField()),
                ('residents', models.BinaryField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.BooleanField()),
                ('terrain', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
            ],
        ),
    ]
