# Generated by Django 4.0.6 on 2022-07-18 20:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetDisplay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=2020, size=20),
        ),
    ]
