# Generated by Django 4.0.6 on 2022-07-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetDisplay', '0002_alter_planet_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='surface_water',
            field=models.IntegerField(),
        ),
    ]
