# Generated by Django 4.0.6 on 2022-07-18 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetDisplay', '0003_alter_planet_surface_water'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planet',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='gravity',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='orbital_period',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='rotation_period',
        ),
    ]
