# Generated by Django 4.0.6 on 2022-07-18 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetDisplay', '0004_remove_planet_diameter_remove_planet_gravity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='residents',
            field=models.IntegerField(),
        ),
    ]
