# Generated by Django 4.0.6 on 2022-07-18 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlanetDisplay', '0005_alter_planet_residents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.CharField(max_length=200),
        ),
    ]
